### ISSUE TITLE
Feature: allow fallback data like the official SWR package

### ISSUE THREAD

**Issue by spiritledsoftware** [Tronikelis/solid-swr#59]
React’s SWR supports passing a 3rd parameter to useSWR which allows the user to provide fallback data (initial data). This would be useful to have.

**Comment by Tronikelis** [comment]
you mean this https://github.com/Tronikelis/solid-swr?tab=readme-ov-file#ssr but scoped to a single hook?

E.g.

```ts
const swr = useSWR(() => key, {fallbackData: {}})
```

**Comment by spiritledsoftware** [comment]
Yes exactly. The original swr package puts it in a 3rd parameter

**Comment by Tronikelis** [comment]
Sure, i will add it

**Comment by Tronikelis** [comment]
https://github.com/Tronikelis/solid-swr/pull/60 just double checking that this is what you meant right?

**Comment by spiritledsoftware** [comment]
Looks great! Thank you
