### ISSUE TITLE
Inconsistent ESM adherence causes ERR_MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by taylor1791** [tronikelis/solid-swr#64]
When I run `npm i solid-swr && node -e 'const {useSwr} = import("solid-swr");'` nodejs throws the following error. I experience this error in node 18, 20, and 22. I believe this is because this package uses `"type": "module"` in package.json, but also ships `.js` as an extension throughout the `dist` directory (instead of `.mjs`). Renaming the appropriate files to .mjs fixes the problem, but this may be undesirable for other reasons.

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/taylor1791/src/tmp/node_modules/solid-swr/dist/core' imported from /home/taylor1791/src/tmp/node_modules/solid-swr/dist/index.js
    at finalizeResolution (node:internal/modules/esm/resolve:257:11)
    at moduleResolve (node:internal/modules/esm/resolve:913:10)
    at defaultResolve (node:internal/modules/esm/resolve:1037:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:650:12)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:599:25)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:582:38)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:241:38)
    at ModuleJob._link (node:internal/modules/esm/module_job:132:49) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///home/taylor1791/src/tmp/node_modules/solid-swr/dist/core'
}
```

I discovered this problem while I was using vitest. If any tested file imports `solid-swr` the same error occurs since vitest [appears](https://github.com/vitest-dev/vitest/discussions/4233) to follow nodejs' module resolution algorithm.

**Comment by tronikelis** [comment]
Thanks for the issue!

Yeah this is because I wanted to avoid adding extra build steps into the library, right now i just run tsc and publish that.

To fix this i would need to use some 3rd party bundler to ship both esm and cjs, maybe you have some suggestions on what to use?

**Comment by tronikelis** [comment]
Or maybe i can try to specify tsc to build different versions, 

In any case ill check it out

**Comment by taylor1791** [comment]
My experiments indicate that your strategy will work (as long as you run `npm run build` before publishing). I couldn't test with your branch because it didn't contain the `dist` directory and the `"files": ["dist"]` property in package.json prevented npm from installing the `src` directory.

This was my first time seeing `tsup` to solve this problem, but it seems like a reasonable wrapper around esbuild and rollup. I was a little bit surprised to see it generate `chunk-DZDTB73T.js`, but I don't think there is anything wrong with it.

**Comment by tronikelis** [comment]
Its not a branch but a version tag, like i wrote you should be able to `npm i` my previous comment

**Comment by tronikelis** [comment]
hmm, seems that `npm i solid-swr@<tag>` is not installing, can you try 

`npm i solid-swr@5.0.1-95c6c365ca5bb666aa990e796a4e84aa`

**Comment by taylor1791** [comment]
@tronikelis The `solid-swr@5.0.1-95c6c365ca5bb666aa990e796a4e84aa` version works great!

**Comment by tronikelis** [comment]
nice, I simplified the package.json a bit, can you try `npm i solid-swr@5.0.1-a97b68c8b253d97b94d65b9fc47cefff` as well?

If it's good then I'll merge it as 5.0.2

**Comment by taylor1791** [comment]
I reviewed #65 and believe it will work well. I also installed `solid-swr@5.0.1-a97b68c8b253d97b94d65b9fc47cefff`to verify it actually works well in the node repl and in vitest.
